export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_START = 'SIGNUP_START';

export const ADD_PROJECTS_SUCCESS ='ADD_PROJECT_SUCCESS';
export const ADD_PROJECTS_START ='ADD_PROJECTS_START';
export const ADD_PROJECTS_START ='ADD_PROJECTS_START';

export const EDIT_PROJECTS_START ='EDIT_PROJECTS_START';
export const EDIT_PROJECTS_START ='EDIT_PROJECTS_START';
export const EDIT_PROJECTS_START ='EDIT_PROJECTS_START';



