export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_START = 'SIGNUP_START';

export const ADD_PROJECTS_SUCCESS ='ADD_PROJECTS_SUCCESS';
export const ADD_PROJECTS_START ='ADD_PROJECTS_START';
export const ADD_PROJECTS_ERROR ='ADD_PROJECTS_ERROR';

export const EDIT_PROJECTS_START ='EDIT_PROJECTS_START';
export const EDIT_PROJECTS_SUCCESS ='EDIT_PROJECTS_SUCCESS';
export const EDIT_PROJECTS_ERROR ='EDIT_PROJECTS_ERROR';

export const DELETE_PROJECTS_SUCCESS ='DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECTS_START ='DELETE_PROJECTS_START';
export const DELETE_PROJECTS_ERROR ='DELETE_PROJECTS_ERROR';


